export const desktopItems = [
  {
    id: "about",
    label: "About Me",
    shortLabel: "ME",
    icon: "about",
    tone: "art",
    position: { x: 12, y: 20 },
    mobile: { x: 17, y: 17 },
    title: "About Me",
    action: "about",
  },
  {
    id: "research",
    label: "Research",
    shortLabel: "R&D",
    icon: "research",
    tone: "art",
    position: { x: 50, y: 14 },
    mobile: { x: 50, y: 17 },
    title: "Research",
    action: "hub",
  },
  {
    id: "angel",
    label: "Angel Desk",
    shortLabel: "A",
    icon: "angel",
    tone: "art",
    position: { x: 88, y: 20 },
    mobile: { x: 83, y: 17 },
    title: "Angel Desk",
    action: "angel",
  },
  {
    id: "work",
    label: "Work",
    shortLabel: "W",
    icon: "work",
    tone: "art",
    position: { x: 20, y: 50 },
    mobile: { x: 17, y: 40 },
    title: "Work",
    action: "hub",
  },
  {
    id: "gallery",
    label: "Gallery",
    shortLabel: "IMG",
    icon: "gallery",
    tone: "art",
    position: { x: 82, y: 50 },
    mobile: { x: 50, y: 40 },
    title: "Gallery",
    action: "gallery",
  },
  {
    id: "stories",
    label: "Unsupervised",
    shortLabel: "BLOG",
    icon: "stories",
    tone: "art",
    position: { x: 30, y: 78 },
    mobile: { x: 83, y: 40 },
    title: "Unsupervised",
    action: "stories",
  },
];

export const portfolioItems = [
  {
    id: "opentrade",
    label: "OpenTrade",
    shortLabel: "OT",
    tone: "blue",
    title: "OpenTrade (YC S26)",
    role: "Machine Learning Engineer",
    date: "Jun 2026 - Sep 2026",
    category: "Industry / ML product",
    summary: "First machine-learning hire for an AI-native investing product.",
    description: [
      "Built the path from live market data to grounded LLM-generated trade cards and the personalized ranking that determined what each user saw.",
      "Turned impressions and downstream behavior into evaluation and training signals for ranking, factual-accuracy, and regression testing.",
    ],
    metrics: [
      "Product grew from launch to about 150K monthly users in two months",
      "Owned the first production model-layer decisions and evaluation spine",
      "Defined launch hypotheses, primary metrics, and guardrails before production releases",
    ],
    tags: ["Machine learning", "LLM evaluation", "Recommendation systems", "Experiment design", "Production inference"],
    links: [{ label: "OpenTrade", href: "https://www.linkedin.com/company/opentradelive/" }],
  },
  {
    id: "r0-systems",
    label: "R0 Systems",
    shortLabel: "R0",
    tone: "red",
    thumbnail: "./assets/gallery/welding.webp",
    title: "R0 Systems",
    role: "Founder & CEO",
    date: "Jun 2024 - Present",
    category: "Plasma hardware / venture",
    summary: "Chemical-free plasma-activated-water equipment for post-harvest produce sanitation.",
    description: [
      "R0 generates produce sanitizer on site from air, water, and electricity. The system combines a patent-pending plasma reactor, microbubble mass transfer, a conveyor wash line, and closed-loop dosing control.",
      "I designed and built the full machine stack: reactor and electrode geometry, a 20 kV driver, STM32 firmware, gas and water handling, mechanical assemblies, fabrication, validation, and field deployment.",
    ],
    metrics: [
      "Bootstrapped to six figures in revenue",
      "Up to 3x shelf-life extension at under $0.50 per ton in energy cost across tomato and leafy-green validation studies",
      "Three peer-reviewed papers and two patents pending",
      "Selected for a16z Speedrun S008",
    ],
    tags: ["Plasma physics", "High-voltage electronics", "Embedded C", "STM32", "PID control", "CAD", "Fabrication"],
    links: [
      { label: "R0 Systems", href: "https://fuckchlorine.com/" },
      { label: "James Dyson Award entry", href: "https://www.jamesdysonaward.org/en-US/2026/project/r0-systems" },
    ],
    media: [
      {
        src: "./assets/gallery/showcase.webp",
        alt: "Tejas receiving an award at the 2026 UW Science and Technology Showcase",
        caption: "UW Science & Technology Showcase, 2026",
      },
    ],
  },
  {
    id: "seal",
    label: "SEAL Lab",
    shortLabel: "SEAL",
    tone: "green",
    title: "SEAL Lab, University of Washington",
    role: "Research Associate",
    date: "Mar 2025 - Nov 2025",
    category: "Embedded sensing / research",
    summary: "Embedded sensing for drowsiness detection and U.S. Navy hull-integrity monitoring.",
    description: [
      "Built a PPG drowsiness wearable with a transimpedance front end, fourth-order Butterworth filtering, 100 Hz 12-bit sampling, and adaptive motion-artifact cancellation.",
      "Built a piezoelectric hull-integrity sensor around a PZT array, charge amplification, and a real-time 512-point FFT at 10 kHz to separate impacts from fatigue-crack acoustic emissions.",
    ],
    metrics: [
      "95% rejection of motion artifact in the PPG pipeline",
      "Reviewed and synthesized more than 40 papers across the sensing programs",
      "Co-wrote technical sections for two funded grant proposals on a seven-person team",
    ],
    tags: ["Analog front ends", "PPG", "Piezoelectric sensing", "DSP", "FFT", "Embedded systems"],
  },
  {
    id: "niist",
    label: "CSIR-NIIST",
    shortLabel: "NIIST",
    tone: "yellow",
    title: "CSIR-NIIST, India",
    role: "Research Associate",
    date: "Jun 2024 - Mar 2025",
    category: "Photovoltaics / materials research",
    summary: "Solar-cell fabrication and characterization in Dr. Suraj Soman's sustainable-energy group.",
    description: [
      "Fabricated dye-sensitized and perovskite solar-cell architectures and ran the characterization stack from device preparation through data interpretation.",
      "Work included IV curves, photo-induced absorption for recombination kinetics, IPCE for spectral response, and XRD with Scherrer grain-size analysis.",
    ],
    metrics: [
      "Built and compared more than 20 device architectures",
      "Worked inside a group holding a world-record dye-sensitized-cell efficiency",
      "Connected photovoltaic materials work to the broader plasma and energy hardware program",
    ],
    tags: ["Perovskites", "Dye-sensitized cells", "IV", "PIA", "IPCE", "XRD", "Cleanroom processing"],
    links: [{ label: "CSIR-NIIST", href: "https://www.niist.res.in/" }],
  },
  {
    id: "ingenium",
    label: "Ingenium",
    shortLabel: "IN",
    tone: "purple",
    title: "Ingenium Naturae",
    role: "Research Engineer",
    date: "May 2023 - Jun 2024",
    category: "Custom hardware / plasma systems",
    summary: "Custom agri-food and plasma equipment for clients and research laboratories.",
    description: [
      "Scoped, designed, fabricated, validated, and delivered working machines across high-voltage power electronics, reactor and electrode architecture, venturis, controls, and mechanical design.",
      "Handled electrical, thermal, fluidic, and mechanical failures on the shop floor until each commissioned machine met its operating requirements.",
    ],
    metrics: [
      "Designed discharge drivers, MOSFET power stages, STM32 firmware, and PID controls",
      "Owned builds from client specification through machine delivery",
    ],
    tags: ["Plasma reactors", "Flyback converters", "MOSFET power stages", "STM32", "Fusion 360", "Machining"],
  },
  {
    id: "research-programs",
    label: "Core Research",
    shortLabel: "LAB",
    tone: "black",
    title: "Core Research",
    subtitle: "Evaluation, reproducibility, and empirical failure modes",
    category: "Independent and collaborative research",
    summary: "Studies with result artifacts, audits, and current status.",
    positionType: "collection",
    entries: [
      {
        title: "MTEB-Gym: label-free embedding evaluation",
        meta: "Research Collaborator / Jun 2026 - Present",
        summary: "Co-developed label-free embedding evaluation and its judge-reliability study.",
        facts: [
          "Co-developed MTEB-Gym, a label-free framework for ranking embedding models on datasets without human relevance annotations.",
          "Worked on bidirectional judging, validation, uncertainty estimates, and failure handling for label-free rankings.",
          "Merged nine changes covering validation, uncertainty estimates, caching, deterministic parallelism, and failure handling.",
          "The active reliability study still needs a public result artifact.",
        ],
        links: [
          { label: "MTEB-Gym contributions", href: "https://github.com/embeddings-benchmark/MTEB-gym-v2/pulls?q=is%3Apr+author%3Atejasnaladala+is%3Amerged" },
          { label: "MTEB contribution", href: "https://github.com/embeddings-benchmark/mteb/pull/4790" },
        ],
      },
      {
        title: "RSNA Knee Abnormality Detection",
        meta: "Independent research / Jul 2026 - Present",
        summary: "A research-grade knee MRI pipeline built around hierarchical 2.5D multiple-instance learning and validation before leaderboard optimization.",
        facts: [
          "Represented each study as ordered slices and preserved study-level structure through slice-to-study aggregation.",
          "Used hierarchical supervision to learn local imaging evidence while producing one study-level abnormality decision.",
          "Built patient/study split, fold-integrity, leakage, label-quality, and metric-consistency audits into the experiment path.",
          "In progress.",
        ],
      },
      {
        title: "AgentBreed",
        meta: "Lead Author / Mar 2026 - Present",
        summary: "A synthetic pilot testing whether richer agent configuration spaces matter more than the search operator used to explore them.",
        facts: [
          "Designed a pre-registered study testing whether multi-agent performance depends more on the available configuration space or the search algorithm.",
          "Ran 700 reproducible evaluations across three domains using a deterministic simulator to separate true effects from LLM sampling noise.",
          "Used equivalence testing and sensitivity analysis to identify which agent-design choices meaningfully affected performance.",
          "The repository contains the tested library, reproduction path, and preregistration for the pending real-LLM replication.",
        ],
        links: [{ label: "GitHub", href: "https://github.com/tejasnaladala/agentbreed" }],
      },
      {
        title: "Procedural-Maze RL Baselines",
        meta: "Lead Author / Feb 2026 - Apr 2026",
        summary: "A procedural-maze study of reward-driven RL, behavior cloning, and a five-line heuristic.",
        facts: [
          "Benchmarked PPO, DQN, and A2C on procedurally generated mazes against simple heuristics and behavior cloning.",
          "The policy class can express strong maze-solving behavior; reward-driven training struggled to reach it consistently.",
          "The public repository includes experiment code, run records, manifests, and a result verifier.",
          "Later runs outgrew the pinned manifest. Artifact reconciliation is in progress before final reporting.",
        ],
        links: [{ label: "GitHub", href: "https://github.com/tejasnaladala/maze-rl-baselines" }],
      },
      {
        title: "Connectome Architecture Benchmark",
        meta: "Independent research / Dec 2025 - Present",
        summary: "An exploratory benchmark asking whether biological wiring helps computation; the original result is invalidated and the corrected protocol awaits a full run.",
        facts: [
          "Built a controlled benchmark testing whether biological connectomes provide better neural-network architectures than matched random graphs.",
          "Audited the original 757-row pilot and withdrew it after finding control-density, provenance, optimizer, and evaluation failures.",
          "Rebuilt CAB v2 around measured digest-bound connectomes, readout-only optimization, and nulls matched on exact edge count and weight distribution.",
          "CAB v2 is implemented and tested. The corrected benchmark awaits a full run. The repository carries no biological-advantage claim.",
        ],
        links: [
          { label: "GitHub", href: "https://github.com/tejasnaladala/connectome-bpu" },
        ],
      },
    ],
  },
  {
    id: "technical-reports",
    label: "Technical Reports",
    shortLabel: "TR",
    tone: "blue",
    title: "Technical Reports",
    subtitle: "Models, serving, and autonomous research systems",
    category: "Reports and research systems",
    summary: "Two measured systems studies and one research-automation project.",
    positionType: "collection",
    entries: [
      {
        title: "Evolutionary optimization of VLM inference",
        meta: "Author / Jun 2026 - Jul 2026",
        summary: "An AlphaEvolve-style search loop over Qwen3-VL inference on CharXiv chart QA.",
        facts: [
          "Used MAP-Elites to search prompt, parsing, formatting, and inference-code variants across a behavioral archive.",
          "Search reached 63.25% held-out; a separately designed per-question router reached 73.0%, compared with the 29.5% naive baseline.",
          "Sandboxed generated code at the AST boundary and retained candidate lineage so every accepted mutation remained inspectable.",
          "Used paired McNemar testing (p = 2.4e-6) to separate the measured gain from evaluation noise.",
        ],
      },
      {
        title: "Dense Qwen vs MoE GLM serving",
        meta: "Author / Jun 2026",
        summary: "An 80-point single-GPU vLLM matrix comparing dense and mixture-of-experts models at roughly equal active-parameter budgets.",
        facts: [
          "Swept prompt length, generation length, concurrency, and serving configuration across Qwen3.5-9B and GLM-4.7-Flash.",
          "Located the dense/MoE throughput crossover near concurrency three.",
          "At 49K-token generation, Qwen admitted 42 concurrent requests versus GLM's 10; GPQA accuracy also moved by 20 points with token budget.",
          "Caught a PCIe-throttled H100 before publishing by reconciling hardware behavior with implausible throughput results.",
        ],
      },
      {
        title: "Parchment Labs",
        meta: "Project Lead / Dec 2025 - Mar 2026",
        summary: "A nine-stage prototype for moving from literature review to an experiment specification.",
        facts: [
          "Ingested papers into a provenance-aware knowledge graph, scored candidate gaps, and retained citations and intermediate reasoning across stages.",
          "Used a three-round review stage to reject weak hypotheses before experiment design.",
          "Its first complete pipeline run generated the original connectome pilot, which was later audited and withdrawn.",
        ],
        links: [
          { label: "Connectome benchmark", href: "https://github.com/tejasnaladala/connectome-bpu" },
        ],
      },
    ],
  },
  {
    id: "publications",
    label: "Publications",
    shortLabel: "PDF",
    tone: "paper",
    title: "Publications",
    subtitle: "Three peer-reviewed papers, 57 citations, h-index 3",
    category: "Peer-reviewed work",
    summary: "Peer-reviewed plasma engineering.",
    positionType: "collection",
    entries: [
      {
        title: "Design of systems for plasma activated water for agri-food applications",
        meta: "Journal of Physics D: Applied Physics 57(49), 493003 / 2024",
        summary: "Misra NN, Naladala T, Alzahrani KJ",
        facts: ["DOI 10.1088/1361-6463/ad77de"],
        links: [{ label: "DOI", href: "https://doi.org/10.1088/1361-6463/ad77de" }],
      },
      {
        title: "Design of a continuous PAW disinfection system for fresh produce industry",
        meta: "Innovative Food Science & Emerging Technologies 97, 103845 / 2024",
        summary: "Misra NN, Naladala T, Alzahrani KJ, Sreelakshmi VP, Negi PS",
        facts: ["DOI 10.1016/j.ifset.2024.103845"],
        links: [{ label: "DOI", href: "https://doi.org/10.1016/j.ifset.2024.103845" }],
      },
      {
        title: "Design and construction of continuous industrial-scale cold plasma equipment",
        meta: "Innovative Food Science & Emerging Technologies 97, 103840 / 2024",
        summary: "Misra NN, Sreelakshmi VP, Naladala T, Alzahrani KJ, Negi PS",
        facts: ["DOI 10.1016/j.ifset.2024.103840"],
        links: [{ label: "DOI", href: "https://doi.org/10.1016/j.ifset.2024.103840" }],
      },
    ],
  },
  {
    id: "field-research",
    label: "Field Research",
    shortLabel: "OOI",
    tone: "green",
    title: "VISIONS '26 / OCEAN 411",
    subtitle: "NSF Ocean Observatories Initiative expedition",
    category: "Ocean field research",
    summary: "Fifteen days aboard R/V Roger Revelle with ROV Jason at Axial Seamount and Southern Hydrate Ridge.",
    positionType: "collection",
    entries: [
      {
        title: "Regional Cabled Array expedition RR2607",
        meta: "Student Researcher / Aug 2026",
        summary: "A field-to-analysis system for estimating methane bubble flux during a 15-day Regional Cabled Array expedition.",
        facts: [
          "Worked across 18 ROV Jason dives at five sites, with instruments deployed and recovered at depths reaching 2,900 m.",
          "Built a provenance-aware multimodal expedition memory that kept shipboard sources read-only and traced derived artifacts to source paths, hashes, and code versions.",
          "Building a multimodal pipeline that aligns computer-vision measurements, sonar-derived acoustic proxies, and field metadata.",
          "Work in progress.",
          "Ran the analysis alongside 4 a.m. CTD casts and chlorophyll, oxygen, RAS, PPS, and microbial-DNA sampling under real field constraints.",
        ],
        links: [
          { label: "VISIONS '26 overview", href: "https://interactiveoceans.washington.edu/about-visions-26/" },
          { label: "VISIONS '26 team", href: "https://interactiveoceans.washington.edu/people-visions26/" },
        ],
      },
    ],
  },
  {
    id: "independent-systems",
    label: "Independent Systems",
    shortLabel: "OSS",
    tone: "purple",
    title: "Independent Systems",
    subtitle: "Public tools, runtimes, robots, and experiments",
    category: "Open source and individual projects",
    summary: "Public tools, runtimes, robots, and experiments.",
    positionType: "collection",
    entries: [
      {
        title: "Mimic",
        meta: "Robotics / Mar 2026",
        summary: "Browser-to-robot imitation learning: WebRTC teleoperation into a MuJoCo Franka arm, demo recording, ACT or diffusion-policy training, and ONNX export.",
        facts: ["Configured 60 Hz control loop", "108 tests", "LeRobot v3 dataset layout"],
        links: [{ label: "GitHub", href: "https://github.com/tejasnaladala/mimic" }],
      },
      {
        title: "Engram",
        meta: "Neuromorphic learning / Apr 2026",
        summary: "A Rust-core continuous-learning prototype with local Hebbian and neuromodulatory updates, persistent memory, and a configurable action-veto layer.",
        links: [{ label: "GitHub", href: "https://github.com/tejasnaladala/engram" }],
      },
      {
        title: "Forge",
        meta: "Agent runtime / Feb 2026",
        summary: "Provider-agnostic multi-agent runtime with declarative agents, eight model-provider families, tools, memory, cost ceilings, and WebSocket observability.",
        facts: ["Python and TypeScript", "FastAPI dashboard", "Apache-2.0"],
        links: [{ label: "GitHub", href: "https://github.com/tejasnaladala/Forge" }],
      },
      {
        title: "WireML",
        meta: "Foundation-model workbench / Apr 2026",
        summary: "A terminal node-graph workbench that wires datasets into CLIP or DINOv2 backbones, trains lightweight heads, and exports ONNX across CUDA, MLX, MPS, ROCm, DirectML, and CPU.",
        links: [{ label: "GitHub", href: "https://github.com/tejasnaladala/wireml" }],
      },
      {
        title: "delphi-quant",
        meta: "Verification / Jan 2026 - May 2026",
        summary: "A retrospective verification prototype for systematic strategies with transaction costs, walk-forward splits, multiple-comparison correction, and structured rejection logs.",
        facts: ["Clean clones currently fall back to synthetic data", "Real-data results are omitted until an immutable input manifest is published"],
        links: [{ label: "GitHub", href: "https://github.com/tejasnaladala/delphi-quant" }],
      },
    ],
  },
];

export const sectionHubs = {
  research: {
    title: "Research",
    subtitle: "Empirical ML, plasma engineering, field science, and public result artifacts.",
    itemIds: ["research-programs", "technical-reports", "publications", "field-research", "independent-systems"],
  },
  work: {
    title: "Work",
    subtitle: "Five roles in machine learning, research, and machine building.",
    itemIds: ["opentrade", "r0-systems", "seal", "niist", "ingenium"],
  },
};

export const workJournal = [
  {
    id: "r0-systems",
    tone: "red",
    title: "Founder & CEO",
    organization: "R0 Systems",
    website: "https://fuckchlorine.com/",
    dates: "Jun 2024 - Present",
    description: [
      "R0 generates produce sanitizer on site using air, water, and electricity. I bootstrapped it to six figures in revenue.",
      "I designed the reactor, Venturi transfer stage, water loop, controls, and field hardware.",
      "The machines now run continuously in customer facilities.",
      "Three peer-reviewed papers, two pending patents, and independent national food-safety laboratory studies document the system.",
      "Demonstrated up to 3x shelf-life extension at under $0.50 per ton in energy cost across tomato and leafy-green validation studies.",
    ],
  },
  {
    id: "opentrade",
    tone: "blue",
    title: "Machine Learning Engineer",
    organization: "OpenTrade",
    website: "https://opentrade.live/",
    dates: "Jun 2026 - Sep 2026",
    description: [
      "As OpenTrade's first ML hire, I built market-data grounding, trade-card generation, and personalized ranking.",
      "Replaced hand-tuned feed ordering with a learned ranking model built from user interaction, content, recency, and market-context signals and evaluated releases through offline replay and product behavior.",
      "Built a factual-accuracy and regression harness for generated financial content, checking grounding against live market data, numerical consistency, temporal validity, unsupported claims, and structured-output compliance across model and prompt releases.",
      "Turned impressions and downstream behavior into evaluation and training signals for subsequent model releases.",
      "Defined launch hypotheses, primary metrics, and guardrails before each production release.",
      "Built backend and serverless API routes serving model outputs, integrated external market-data providers, and owned testing, deployment, and CI for a product that grew from launch to roughly 150,000 monthly users in two months.",
    ],
  },
  {
    id: "seal",
    tone: "green",
    title: "Research Associate",
    organization: "Sensors, Energy, and Automation Laboratory (SEAL)",
    website: "https://www.uwseal.org/",
    dates: "Mar 2025 - Nov 2025",
    description: [
      "Engineered a real-time PPG wearable: transimpedance front end, fourth-order Butterworth filter, 100 Hz 12-bit acquisition, and adaptive motion-artifact cancellation rejecting 95% of motion artifact.",
      "Built a PZT-array acoustic-emission system for U.S. Navy hull-integrity monitoring, using charge amplification, 10 kHz acquisition, and a real-time 512-point FFT pipeline to separate impacts from fatigue-crack signatures.",
      "Handled analog design, prototype bring-up, embedded acquisition, signal processing, bench characterization, and failure analysis.",
      "Authored the sensing architecture, signal-processing methodology, and validation sections of two funded proposals across a seven-person research team.",
    ],
  },
  {
    id: "niist",
    tone: "yellow",
    title: "Research Associate",
    organization: "CSIR-NIIST",
    website: "https://www.niist.res.in/",
    dates: "Jun 2024 - Mar 2025",
    description: [
      "Researched dye-sensitized and perovskite photovoltaics within CSIR-NIIST's indoor-light energy-harvesting program, whose dye-sensitized-cell work later reached a 40% indoor-light conversion-efficiency record.",
      "Fabricated complete solar-cell devices using FTO substrates, TiO₂ photoanodes, thermal processing, ruthenium sensitizers, electrolytes, counter electrodes, and sealed assemblies.",
      "Ran the full optoelectronic and structural characterization stack: J–V curves, IPCE, photoinduced absorption spectroscopy, and XRD with Scherrer crystallite-size analysis.",
      "Connected spectral response, charge-recombination behavior, crystallite structure, and fabrication parameters to device-level efficiency and failure modes.",
      "Designed controlled experiments across photoanode architecture and processing conditions, then analyzed batch variation and reproducibility across fabricated devices.",
    ],
  },
  {
    id: "ingenium",
    tone: "purple",
    title: "Research Engineer",
    organization: "Ingenium Naturae",
    dates: "May 2023 - Jun 2024",
    description: [
      "Delivered custom plasma and automation machines for agri-food clients. Each build combined power electronics, embedded control, fluidics, reactor design, and industrial mechanics.",
      "Designed 20 kV discharge drivers, MOSFET switching stages, PID control loops, STM32 firmware, electrode and reactor geometries, Venturi injectors, and production CAD assemblies.",
      "Handled client specifications, system architecture, component selection, fabrication, wiring, firmware, validation, acceptance testing, documentation, and handoff.",
      "Debugged coupled electrical, thermal, fluidic, and mechanical failure modes on the shop floor until each machine met its operating requirements.",
    ],
  },
];

export const researchJournal = {
  studies: [
    {
      groupId: "research-programs",
      entryTitle: "MTEB-Gym: label-free embedding evaluation",
      field: "Embedding evaluation",
      question: "When can label-free embedding evaluation produce a trustworthy model ranking?",
      dates: "Jun 2026 - Present",
      website: "https://github.com/embeddings-benchmark/MTEB-gym-v2/pulls?q=is%3Apr+author%3Atejasnaladala+is%3Amerged",
      description: [
        "Co-developed MTEB-Gym, a label-free framework for ranking embedding models on datasets without human relevance annotations.",
        "Worked on bidirectional judging, validation, uncertainty estimates, and failure handling for label-free rankings.",
        "Merged nine changes covering validation, uncertainty estimates, caching, deterministic parallelism, and failure handling.",
      ],
      finding:
        "Nine merged upstream changes cover validation, uncertainty estimates, cache behavior, deterministic parallelism, and failure handling.",
      tension:
        "The active reliability study still needs a public result artifact.",
    },
    {
      groupId: "research-programs",
      entryTitle: "RSNA Knee Abnormality Detection",
      field: "Medical imaging",
      question: "Which validation choices materially change a knee-MRI model's reported AUC?",
      kind: "project",
      dates: "Jul 2026 - Present",
      description: [
        "A knee-MRI evaluation pipeline built around ordered slices, hierarchical 2.5D multiple-instance learning, and study-level aggregation.",
        "Patient/study splits, fold-integrity checks, leakage audits, label-quality analysis, and metric-consistency tests run inside the experiment path.",
        "In progress.",
      ],
      finding:
        "The current artifact covers study-level aggregation, leakage checks, fold audits, and metric-consistency tests.",
      tension:
        "In progress.",
    },
    {
      groupId: "research-programs",
      entryTitle: "AgentBreed",
      field: "Multi-agent systems",
      question: "How much agent performance comes from the configuration space, and how much from the search operator?",
      dates: "Mar 2026 - Present",
      website: "https://github.com/tejasnaladala/agentbreed",
      description: [
        "Designed a pre-registered study of configuration-space richness and search algorithms in multi-agent systems.",
        "Ran 700 reproducible evaluations across three domains in a deterministic simulator.",
        "Used equivalence testing and sensitivity analysis to identify agent-design choices with measurable effects.",
        "The real-LLM replication is preregistered and pending; current results cover the simulator.",
      ],
      finding:
        "A 700-run deterministic synthetic pilot found that configuration-space richness mattered more than the choice among several search operators.",
      tension:
        "The real-LLM replication is preregistered and pending. Current results come from the deterministic simulator.",
    },
    {
      groupId: "research-programs",
      entryTitle: "Procedural-Maze RL Baselines",
      field: "Reinforcement learning",
      question: "Why did modern reward-driven RL miss a policy a five-line heuristic could see?",
      dates: "Feb 2026 - Apr 2026",
      website: "https://github.com/tejasnaladala/maze-rl-baselines",
      description: [
        "Benchmarked PPO, DQN, and A2C on procedurally generated mazes against simple heuristics and behavior cloning.",
        "The policy class can express strong maze-solving behavior; reward-driven training struggled to reach it consistently.",
        "The public repository includes experiment code, run records, manifests, and a result verifier.",
        "Later runs outgrew the pinned manifest. Artifact reconciliation is in progress before final reporting.",
      ],
      finding:
        "The policy class can express strong maze-solving behavior; reward-driven training struggled to reach it consistently.",
      tension:
        "Later runs outgrew the pinned manifest. Artifact reconciliation is in progress before final reporting.",
    },
    {
      groupId: "research-programs",
      entryTitle: "Connectome Architecture Benchmark",
      field: "Biological computation",
      question: "Does biological wiring still help after density, weights, graph realizations, and trainable components are actually controlled?",
      dates: "Dec 2025 - Present",
      website: "https://github.com/tejasnaladala/connectome-bpu",
      description: [
        "Built a controlled benchmark for biological connectomes and matched random graphs.",
        "Audited and invalidated the original 757-row pilot after finding control-density, provenance, optimizer, and evaluation failures.",
        "Rebuilt CAB v2 around digest-bound measured connectomes, readout-only optimization, and nulls matched on exact edge count and weight distribution.",
        "CAB v2 is implemented and tested. The full corrected run is pending.",
      ],
      finding:
        "The first pass found confounds in null-graph density, weight distributions, dataset provenance, and what the optimizer was allowed to train.",
      tension:
        "The original 757-row artifact is invalidated. CAB v2 awaits a full corrected run.",
    },
    {
      groupId: "field-research",
      entryTitle: "Regional Cabled Array expedition RR2607",
      field: "Ocean field science",
      question: "Can methane-bubble flux be estimated while the experiment is 2,900 meters underwater?",
      kind: "project",
      dates: "Aug 2026 - Present",
      website: "https://interactiveoceans.washington.edu/about-visions-26/",
      description: [
        "Building a field-to-analysis system for methane-bubble flux estimation from ROV video, sonar, hydrophone, CTD, and navigation data.",
        "The provenance layer keeps shipboard sources read-only and traces every derived artifact to source paths, hashes, and code versions.",
        "Current work covers computer vision, acoustic alignment, calibration, and held-out validation.",
        "Work in progress.",
      ],
      finding:
        "Building a provenance-aware pipeline that aligns computer vision, sonar, and field metadata.",
      tension:
        "Work in progress.",
    },
  ],
  reports: [
    {
      groupId: "technical-reports",
      entryTitle: "Evolutionary optimization of VLM inference",
      displayTitle: "VLM Inference Optimization",
      attribution: "Advised by Professor Zhuang Liu · Princeton University",
      dates: "Jun 2026 - Jul 2026",
      description: [
        "An AlphaEvolve-style search loop improved the best single-prompt Qwen3-VL configuration to 63.25% held-out accuracy on CharXiv chart QA.",
        "MAP-Elites searched prompt, parsing, formatting, and inference-code variants across a behavioral archive.",
        "A separately designed per-question router reached 73.0%, compared with the 29.5% naive baseline.",
        "The paired comparison gave p = 2.4e-6, and every accepted mutation retained inspectable lineage.",
      ],
      note: "Search reached 63.25% held-out; a separately designed per-question router reached 73.0%.",
    },
    {
      groupId: "technical-reports",
      entryTitle: "Dense Qwen vs MoE GLM serving",
      displayTitle: "Single-GPU Model Serving",
      attribution: "Advised by Professor Juncheng Yang · Harvard University",
      dates: "Jun 2026",
      description: [
        "An 80-point vLLM matrix comparing dense and mixture-of-experts models at roughly equal active-parameter budgets.",
        "The benchmark swept prompt length, generation length, concurrency, and serving configuration across Qwen3.5-9B and GLM-4.7-Flash.",
        "The dense/MoE throughput crossover appeared near concurrency three. At 49K-token generation, Qwen admitted 42 concurrent requests versus GLM's 10.",
        "A hardware audit caught a PCIe-throttled H100 before publication; GPQA accuracy moved by 20 points with token budget.",
      ],
      note: "An 80-point serving matrix found the dense/MoE crossover near concurrency three, after catching a PCIe-throttled H100.",
    },
    {
      groupId: "technical-reports",
      entryTitle: "Parchment Labs",
      kind: "project",
      displayTitle: "Parchment Labs",
      attribution: "Literature-to-experiment research automation",
      dates: "Dec 2025 - Mar 2026",
      description: [
        "A nine-stage prototype for moving from literature review to an experiment specification.",
        "It ingested papers into a provenance-aware graph, scored candidate gaps, and retained citations and intermediate reasoning across stages.",
        "A three-round review stage rejected weak hypotheses before experiment design.",
        "Its first complete pipeline run generated the original connectome pilot, which was later audited and withdrawn.",
      ],
      note: "A nine-stage literature-to-experiment system that produced the connectome benchmark as its first full study.",
    },
  ],
  publications: [
    {
      title: "Design of systems for plasma activated water for agri-food applications",
      meta: "Journal of Physics D: Applied Physics 57(49), 493003 / 2024",
      website: "https://doi.org/10.1088/1361-6463/ad77de",
    },
    {
      title: "Design of a continuous PAW disinfection system for fresh produce industry",
      meta: "Innovative Food Science & Emerging Technologies 97, 103845 / 2024",
      website: "https://doi.org/10.1016/j.ifset.2024.103845",
    },
    {
      title: "Design and construction of continuous industrial-scale cold plasma equipment",
      meta: "Innovative Food Science & Emerging Technologies 97, 103840 / 2024",
      website: "https://doi.org/10.1016/j.ifset.2024.103840",
    },
  ],
  systems: [
    {
      title: "Mimic",
      description: "Browser teleoperation and imitation learning for a simulated Franka arm.",
      website: "https://github.com/tejasnaladala/mimic",
    },
    {
      title: "Engram",
      description: "Online learning with local plasticity, persistent memory, and safety gates.",
      website: "https://github.com/tejasnaladala/engram",
    },
    {
      title: "Forge",
      description: "Provider-agnostic agents with tools, memory, budgets, and observability.",
      website: "https://github.com/tejasnaladala/Forge",
    },
    {
      title: "WireML",
      description: "A terminal workbench for training lightweight heads on foundation-model embeddings.",
      website: "https://github.com/tejasnaladala/wireml",
    },
    {
      title: "delphi-quant",
      description: "A verification harness for systematic strategies and legible rejection.",
      website: "https://github.com/tejasnaladala/delphi-quant",
    },
  ],
};

export const aboutTabs = {
  hello: {
    label: "Hello",
    count: "01",
    intro: "My name is Tejas. I'm from India, so yes, you pronounce the 'j'.",
    buildLine: "I'm 19. I build and research full-time.",
    paragraphs: [
      "I'm Tejas, a 19-year-old Engineering student at the University of Washington.",
      "I founded R0 Systems and run empirical ML studies across embedding evaluation, medical imaging, agents, and reinforcement learning.",
    ],
    capabilities: ["AI/ML evaluation", "Plasma engineering", "Embedded systems", "Research automation", "Software prototypes", "Hardware fabrication"],
  },
  offclock: {
    label: "Off clock",
    count: "05",
    intro: "Serious about the work. Still capable of laughing at myself.",
    items: [
      ["Beatboxing", "I have beatboxed at founder dinners, on stages, and in rooms where a safer person would have stayed quiet."],
      ["Dancing", "Usually freestyle, occasionally choreographed, always taken more seriously than the warm-up suggests."],
      ["Movement", "Gym, swimming, long Seattle walks, and any side quest that starts after midnight."],
      ["Coffee", "Enough of an obsession to reverse-engineer a Nespresso barcode system."],
      ["Languages", "English, Telugu, and Hindi; conversational Mandarin."],
    ],
  },
  signals: {
    label: "Signals",
    count: "26",
    intro: "A few useful coordinates.",
    items: [
      ["Research", "Three peer-reviewed papers, 57 citations, h-index 3, plus current work in MTEB, medical imaging, RL, and connectomes."],
      ["Building", "R0 Systems and a public trail of robotics, agents, evaluation tools, and ML experiments on GitHub."],
      ["Programs", "a16z Speedrun S008, Startup School 2026, Founders Inc pitch day, Z Fellows, and the UW Lavin Entrepreneurship Program."],
      ["Recognition", "CMU Venture Challenge runner-up; UW Science & Technology Showcase Grand Prize and Best Communication; Red Bull Basement runner-up."],
      ["Fieldwork", "VISIONS '26 student researcher aboard R/V Roger Revelle with ROV Jason."],
    ],
  },
};

export const aboutNarrative = {
  roots: [
    [
      "My roots lie in a ",
      { text: "small coastal village in South India", mark: true, tone: "green", color: true },
      ".",
    ],
    [
      "My family farmed for generations. We grew chilli, tobacco, and other food crops. I grew up with all of it. The land, the crops, the people, the chemicals, the machines, and even the money problems in a traditional Indian family dynamic.",
    ],
  ],
  education: [
    [
      "I now study engineering at the ",
      { text: "University of Washington", mark: true, tone: "blue" },
      ", though I don't really believe in formal education.",
    ],
    [
      "Academically, I was far from exceptional. I never cared enough to study for grades. My dad once dropped a course and retook it the next semester because he got a ",
      "97 instead of a 100",
      ". That was why we couldn't ever have a peaceful relationship while I was growing up. He was a perfectionist. I believed ",
      { text: "imperfections were sometimes what made things perfect", mark: true, tone: "pink" },
      ".",
    ],
  ],
  stage: [
    [
      "I fell in love with the art of ",
      { text: "\"fuck around and find out\"", mark: true, tone: "coral", color: true },
      ".",
    ],
    [
      "I cared about completely different things. I would break open my ceiling fan to see if I could make it spin in reverse. I would try building my own hydroponic irrigation system. I would change how my coffee machine brewed coffee. I would try Pavloving different animals into doing chores for me. Yes, my dog is more capable than a $20,000 ",
      { text: "Unitree G1", href: "https://robostore.com/products/unitree-g1-robotic-humanoid", tone: "coral" },
      " at doing laundry.",
    ],
    [
      "I picked up ",
      { text: "beatboxing", href: "https://en.wikipedia.org/wiki/Beatboxing", tone: "gold" },
      ", then dance, street plays, drama, debate, and pageants. I performed in front of ",
      { text: "tens of thousands of people", mark: true, tone: "pink" },
      ". I led blood, book, and clothing donation drives. I led a thousand students as school captain.",
    ],
    "I loved it. I loved being on stage. I loved people. I loved making people laugh. I loved being the chaos and also being the person who could hold it together.",
    "I started doing things that made me happy.",
    [
      "and somewhere along the way, I ",
      { text: "fell in love with problems", mark: true, tone: "rose" },
      ".",
    ],
  ],
  freedomIntro: [
    { text: "entrepreneurship", mark: true, tone: "coral" },
    " speaks to me",
  ],
  freedom: [
    "Freedom to not have my entire life decided for me or imposed upon me because of societal norms.",
    "Freedom to become obsessed with something nobody around me understands yet.",
    "Freedom to build something because I think it should exist.",
    "Freedom to change direction when I realise I was wrong.",
    "Freedom to work with people I actually respect.",
    "Freedom to fail on my own terms.",
    "Freedom to change lives.",
    "Freedom to be me.",
  ],
  freedomClose: "So I started building.",
  builds: [
    {
      label: "power",
      content: [
        "I have built ",
        { text: "high-voltage power electronics", mark: true, tone: "gold" },
        " and sold plasma reactors.",
      ],
    },
    {
      label: "sensing",
      content: [
        "I built hull-integrity sensing hardware for a ",
        { text: "U.S. Navy", mark: true, tone: "blue" },
        " project and deployed subsea instrumentation in the Pacific.",
      ],
    },
    {
      label: "ocean",
      content: [
        "I built computer-vision and event-logging pipelines during work with ",
        { text: "WHOI", href: "https://www.whoi.edu/", tone: "blue" },
        ", ",
        { text: "NSF's OOI", href: "https://oceanobservatories.org/", tone: "sky" },
        ", and UW ",
        { text: "APL", href: "https://www.apl.washington.edu/", tone: "green" },
        ".",
      ],
    },
    {
      label: "fieldwork",
      content: [
        "I surveyed the Axial Seamount, the most active underwater volcano in the Pacific Northwest, 300 miles off the coast of Oregon, using an ",
        { text: "11,000-pound robot", href: "https://www.whoi.edu/what-we-do/explore/underwater-vehicles/ndsf-jason/", tone: "blue" },
        ".",
      ],
    },
    {
      label: "scale",
      content: [
        "At ",
        { text: "OpenTrade", href: "https://opentrade.live/", tone: "green" },
        ", I built the model-evaluation and ranking stack for a product that reached ",
        { text: "0 to 150,000 users in two months", mark: true, tone: "coral" },
        ".",
      ],
    },
    {
      label: "benchmarks",
      content: [
        "I collaborated on ",
        { text: "MTEB", href: "https://pypi.org/project/mteb/", tone: "pink" },
        ". The package reached roughly ",
        { text: "17 million PyPI downloads by August 2026", mark: true, tone: "pink" },
        ".",
      ],
    },
    {
      label: "empiricism",
      content: [
        "I built a knee-MRI research pipeline around a ",
        { text: "Radiological Society of North America", href: "https://www.rsna.org/", tone: "sky" },
        " challenge dataset.",
      ],
    },
    {
      label: "materials",
      content: [
        "I fabricated and characterised ",
        { text: "dye-sensitised solar-cell architectures", mark: true, tone: "green" },
        " with ",
        { text: "the group behind the world-record efficiency", href: "https://www.niist.res.in/", tone: "gold" },
        ".",
      ],
    },
    {
      label: "publications",
      content: [
        "I published ",
        { text: "3 peer-reviewed papers", mark: true, tone: "coral" },
        ", 2 technical reports, and presented at an international conference.",
      ],
    },
  ],
  questions: [
    [
      "I'm also intrigued by psychedelics, ego death, consciousness, religion, God, ambition, love, and ",
      { text: "what it means to be human", mark: true, tone: "green" },
      ".",
    ],
    "Spirituality often confuses me.",
    [
      { text: "Curiosity", mark: true, tone: "green", color: true },
      " is the only thing tying this page together.",
    ],
  ],
  ending: [
    "I'm getting at something here. I promise.",
  ],
};

export const angelProfile = {
  title: "Angel Desk",
  eyebrow: "PERSONAL CHECKS / VERY EARLY",
  thesis: [
    {
      id: "agentic-commonwealth",
      label: "Agentic Commonwealth",
      definition: "Core infrastructure for intelligent systems: agent platforms, data systems, developer tooling, future-of-work software, and agent optimization through reinforcement learning.",
    },
    {
      id: "american-dynamism",
      label: "American Dynamism",
      definition: "Technologies that expand industrial capacity and strategic resilience across advanced manufacturing, energy, aerospace, and uncrewed systems.",
    },
    {
      id: "kinetic-sovereignty",
      label: "Kinetic Sovereignty",
      definition: "Deeptech and hardtech that translate intelligence into physical capability across climate, agriculture, robotics, and physical AI.",
    },
  ],
  lead: "I write personal $5K-$30K checks into very early technical teams.",
  paragraphs: [
    "I am most useful before the story gets polished. I love it when technical insight does most of the talking.",
    "No warm introductions are required, but managing to find one gets you brownie points.",
    "I don't care for decks. A Google Doc is more than enough. Clarity of thought is what I look for.",
  ],
  referral: "If I like you but I'm not in a position to fund you, I will personally refer you to investment partners at Founders, Inc. and a16z Speedrun.",
  scorecardIntro: "There is no formula for predicting which startups become unicorns, but these signals make me want to hop on a Google Meet with you. I call it the 20-point rule.",
  signals: [
    { label: "Team synergy & story", score: "+5" },
    { label: "High agency and proof of building, failing, and learning", score: "+4" },
    { label: "Honesty & asking for help", score: "+4" },
    { label: "A technical edge", score: "+2" },
    { label: "A non-cliched contrarian take on the world", score: "+1" },
    { label: "A working artifact, however ugly", score: "+1" },
    { label: "Evidence-backed pivots", score: "+1 each, max +3" },
  ],
};

export const cvProfile = {
  title: "Complete CV",
  updated: "Updated Sep 2026",
  summary: "Work, research, publications, technical reports, open-source systems, awards, and engineering tools.",
  highlights: [
    "R0 Systems, OpenTrade, SEAL, CSIR-NIIST, and Ingenium Naturae",
    "MTEB-Gym, RSNA knee imaging, agentbreed, maze RL, connectomes, and VISIONS '26",
    "Three peer-reviewed publications and two technical reports",
    "Selected open-source systems, awards, programs, patents, and skills",
  ],
};

export const galleryItems = [];

export const archiveEntries = [
  {
    id: "nespresso-jailbreak",
    title: "the nespresso jailbreak",
    meta: "coffee / optical codes / unreasonable persistence",
    teaser: "I reverse-engineered the five-parameter barcode around a Vertuo pod, then generated my own recipes.",
    readingTime: "Estimated reading time: 4 minutes 34 seconds",
    blocks: [
      { type: "paragraph", text: "My dad owns a Nespresso Vertuo, and I am the kind of person who loves coffee more than I loved my ex. Not in the normal \"I am addicted to caffeine or I can't take a shit in the morning\" way. I mean Nikki-level obsession, from the movie Obsession." },
      { type: "paragraph", text: "The Vertuo should have been perfect for me: insert a capsule, press a button, get coffee, drink. Instead, the simplicity annoyed the \"shit\" out of me, pun intended." },
      { type: "paragraph", text: "Around the underside of every capsule's rim is a ring of black and reflective marks. An optical reader scans that ring, and the machine uses it to choose the brew program, which, as I figured, included water volume, temperature, flow, pre-infusion time, and capsule rotation. Nespresso describes those same controls as \"capsule-specific extraction parameters.\"" },
      { type: "pullquote", text: "Most people see convenience." },
      { type: "pullquote", text: "I saw a machine being forced to obey instructions from a sticker. And me being forced to the same five coffee flavours." },
      { type: "doodle", art: "capsule-code" },
      { type: "paragraph", text: "I started collecting used capsules. My mom said she'd lend me an extra $50 if I was in need. I washed them, dried them, labelled them, and photographed the code rings. The first images were useless, with curved bars, glare from the foil, dents in the rim, and tiny camera-angle changes that distorted the widths." },
      { type: "paragraph", text: "I wrote a small image-processing script that found the circular rim, sampled a narrow annulus around it, and \"unwrapped\" the circle into a straight strip. I thresholded it, measured run lengths, and compared the repeating sections." },
      { type: "doodle", art: "unwrap" },
      { type: "paragraph", text: "Then came the slower part. A code can be decoded only if you know what its symbols correspond to, and the coffee itself was a confounding variable. Official capsules differ in grind, dose, roast, and coffee-bed resistance. If one brewed more slowly than another, I couldn't blame the barcode." },
      { type: "paragraph", text: "So I built controls." },
      { type: "paragraph", text: "I cleaned several capsule shells, filled them with the same coffee at the same grind and dose, sealed them as consistently as I could, and changed the code ring while keeping the coffee bed fixed." },
      { type: "question", text: "The research question: when the physical contents stay approximately constant, what does changing only the code make the machine do?" },
      { type: "paragraph", text: "My kitchen became a very small, very caffeinated test bench." },
      { type: "doodle", art: "test-bench" },
      { type: "paragraph", text: "A scale under the cup gave me beverage mass instead of an eyeballed mug measurement. A temperature probe near the outlet recorded the liquid's temperature profile; mass over time gave me the flow curve. The delay between the cycle's beginning and the first sustained liquid reaching the cup gave me an approximate measure of pre-infusion and startup timing." },
      { type: "paragraph", text: "Spin speed was the least cooperative parameter." },
      { type: "paragraph", text: "I could hear that different capsules produced different motor profiles. I recorded the machine and examined the frequency spectrum of the motor whine. Its dominant frequency gave me a consistent proxy for relative rotational speed." },
      { type: "paragraph", text: "It was not a factory-calibrated tachometer, but it was enough to distinguish different spin stages." },
      { type: "doodle", art: "spectrum" },
      { type: "paragraph", text: "At this point I was proud enough of myself, and wanted to see if anyone was hiring a reverse-engineering intern." },
      { type: "pullquote", text: "This optical pattern produces this volume class. This one produces this timing profile. This section appears to affect temperature. This combination changes the machine's relative rotation behaviour." },
      { type: "paragraph", text: "Enough pods began to form clusters. I compared pairs, looked for segments that stayed fixed when an output stayed fixed, and tracked which segments changed when one observable shifted." },
      { type: "paragraph", text: "Once I could move from barcode to behaviour, I tried to move backward, from desired behaviour to barcode." },
      { type: "paragraph", text: "Eventually, I pressed the button and the machine accepted one." },
      { type: "sequence", lines: ["It spun.", "Paused.", "Infused.", "Accelerated.", "And poured."] },
      { type: "paragraph", text: "It saw a sufficiently valid optical instruction and executed it." },
      { type: "doodle", art: "brew" },
      { type: "paragraph", text: "From there, I generated a small library of custom profiles within the machine's existing operating envelope: a shorter, more concentrated brew; a gentler profile for a lighter roast; and a longer cup that did not simply drown the grounds in water." },
      { type: "paragraph", text: "I applied the rings to third-party shells and changed one variable at a time. Some recipes were terrible." },
      { type: "paragraph", text: "All of them taught me something." },
      { type: "paragraph", text: "This was about refusing to accept that the button was the end-all, be-all of the system." },
      { type: "stack", lines: ["Behind the button was an optical sensor.", "Behind the sensor was a code.", "Behind the code was a control policy.", "Behind the control policy were assumptions about what kinds of coffee I was allowed to make.", "And assumptions are always invitations."] },
      { type: "doodle", art: "policy" },
      { type: "paragraph", text: "This is an unreasonable amount of effort to spend on a cup of coffee. That is exactly why I love the story." },
      { type: "closing", lines: ["It was just coffee.", "It is never just coffee."] },
    ],
  },
  {
    id: "wifi-cantenna",
    title: "the cantenna incident",
    meta: "2.4 GHz / a Pringles can / dorm engineering",
    teaser: "The dorm Wi-Fi was unusable, so I built a directional antenna and pointed it through two concrete walls.",
    readingTime: "Estimated reading time: 4 minutes 52 seconds",
    blocks: [
      { type: "pullquote", text: "\"Unauthorized Use of Snack Packaging as Network Infrastructure\" was my first dorm violation as a freshman." },
      { type: "paragraph", text: "Freshman year, I was assigned a dorm room on the far side of the building, which apparently meant the far side of modern civilization." },
      { type: "paragraph", text: "The Wi-Fi signal at my desk averaged around -85 dBm. On a good day." },
      { type: "paragraph", text: "-85 dBm means your laptop is technically connected, but only because neither party has had the courage to end the relationship. Canvas loaded one rectangle at a time. Video calls made me look like a police sketch. Submitting an assignment at 11:58 became a live demonstration of probability theory." },
      { type: "paragraph", text: "I sent campus IT screenshots, signal readings, and the room location." },
      { type: "paragraph", text: "Their answer was that the access point could not be moved. Their proposed fix was that I could work in the common area." },
      { type: "pullquote", text: "Incredible. Years of networking research, billions of wireless devices, and the solution was still \"go sit somewhere else.\"" },
      { type: "paragraph", text: "I tried everything normal first. I moved the desk, changed adapter settings, and tested the signal by the door, window, and ceiling. At one point I was standing on a chair holding my laptop above my head, which is usually when an engineering solution stops looking intelligent." },
      { type: "paragraph", text: "The signal improved slightly in one upper corner. That was enough. There was a path into the room. It was just weak, ugly, and probably bouncing through the hallway before arriving." },
      { type: "doodle", art: "wifi" },
      { type: "section-heading", text: "Proposed corrective action" },
      { type: "pullquote", accent: true, text: "Build a directional antenna." },
      { type: "paragraph", text: "Not hack the network. Not steal a password. Not build a jammer. Nothing sexy enough for a disciplinary hearing." },
      { type: "paragraph", text: "A normal laptop antenna listens in several directions. I knew roughly where the access point was. A directional antenna could trade broad coverage for gain in the one direction I cared about." },
      { type: "paragraph", text: "I started reading about cantennas, which are exactly what the name suggests: antennas made from cans." },
      { type: "paragraph", text: "The classic design uses a conductive cylinder as a circular waveguide. A probe inside excites the field, the sealed end acts as a reflector, and the open end gives the antenna directionality." },
      { type: "paragraph", text: "At 2.4 GHz, the free-space wavelength is about 125 millimetres. A quarter wavelength is a little over 30 millimetres, which gave me the initial probe length. The feed position depends on the guide wavelength inside the cylinder, which depends on its diameter and cutoff frequency." },
      { type: "pullquote", text: "This is where I discovered that most tutorials treat \"can\" as a legally sufficient unit of measurement. It is not." },
      { type: "paragraph", text: "A Pringles tube is not an ideal waveguide either. Its diameter sits close to the lower practical limit for 2.4 GHz, and its conductive lining is considerably less impressive once you attack it with a multimeter." },
      { type: "paragraph", text: "I considered buying a proper metal can." },
      { type: "paragraph", text: "Then I remembered the project was already funny." },
      { type: "doodle", art: "cantenna" },
      { type: "section-heading", text: "Bill of materials" },
      { type: "list", items: ["One Pringles can.", "One N-type bulkhead connector.", "One SMA pigtail.", "One USB Wi-Fi adapter with an external antenna port.", "Copper wire and copper tape.", "A camera tripod.", "One multimeter.", "A completely unjustified level of confidence."] },
      { type: "paragraph", text: "The chips did not contribute electrically, but I ate them during design review." },
      { type: "doodle", art: "chips" },
      { type: "section-heading", text: "Construction notes" },
      { type: "paragraph", text: "I checked continuity across the inner lining and reinforced weak sections with copper tape. I wanted the cylinder, base, and connector body to behave as one conductive structure rather than three objects loosely sharing a snack logo." },
      { type: "paragraph", text: "I soldered copper wire to the centre pin of the N-type connector and trimmed it toward a quarter wavelength. I left it slightly long because wire can always be shortened. It cannot be emotionally encouraged to grow back." },
      { type: "paragraph", text: "I marked the feed hole about 45 millimetres from the sealed end, based on the dimensions and design I was adapting. I measured it three times, then another four because drilling into cardboard should not have felt this permanent." },
      { type: "paragraph", text: "The connector went through the tube. The SMA pigtail ran to the USB adapter. The adapter plugged into my laptop." },
      { type: "paragraph", text: "I was not going to claim the finished antenna had exactly 12 dBi of gain. I did not own a calibrated reference antenna, a network analyser, or an anechoic chamber. People throw precise gain numbers around online because confidence is free." },
      { type: "paragraph", text: "What I could measure was whether the link got better." },
      { type: "doodle", art: "connector" },
      { type: "section-heading", text: "Test procedure" },
      { type: "paragraph", text: "I mounted the antenna on a camera tripod and opened a signal monitor. The tripod let me adjust direction, elevation, and polarization without holding a Pringles can perfectly still for twenty minutes. It also made the device look official, which is an underappreciated part of engineering." },
      { type: "beats", lines: ["I swept it slowly across the wall.", "Nothing.", "I changed the elevation.", "Still nothing.", "I rotated it slightly past where I thought the access point should be.", "The signal jumped.", "I turned away. It dropped.", "I turned back. It rose again."] },
      { type: "pullquote", accent: true, text: "This was the first time a Pringles can had given me positive experimental results instead of salt." },
      { type: "paragraph", text: "The best direction was slightly off to one side, probably because the useful signal was reflecting through a doorway or corridor rather than travelling directly through two concrete walls like the Kool-Aid Man." },
      { type: "paragraph", text: "I adjusted the angle in small increments, rotated the polarization, shortened the cable to reduce loss, and raised the tripod. Every time the signal improved, I marked the position with tape." },
      { type: "paragraph", text: "My roommate asked why." },
      { type: "pullquote", text: "Because optimization is useless if some idiot bumps the tripod while looking for socks." },
      { type: "doodle", art: "spectrum" },
      { type: "section-heading", text: "Results" },
      { type: "paragraph", text: "The connection went from barely alive to stable enough for actual work." },
      { type: "paragraph", text: "The signal climbed out of the -80s. Packet loss fell. Latency stopped spiking whenever I attempted something more demanding than opening a text file. The best speed tests reached about 150 Mbps, although dorm traffic still moved the number around." },
      { type: "paragraph", text: "That was fine. I was not providing internet to the International Space Station. I wanted Canvas to open before I graduated." },
      { type: "paragraph", text: "The cantenna stayed mounted for the entire semester." },
      { type: "section-heading", text: "Housing review" },
      { type: "paragraph", text: "One afternoon, the RA walked in and stared at the tripod." },
      { type: "dialogue", lines: ["\"What is that?\"", "\"An art project.\"", "He looked at the cable.", "\"What kind of art?\"", "\"Site specific.\"", "He kept staring."] },
      { type: "paragraph", text: "I explained that it was a passive directional antenna connected to my own Wi-Fi adapter. I was not modifying the adapter's transmit power, attacking the network, or touching anyone else's connection. I had simply built a better radio link for the signal already reaching my room." },
      { type: "paragraph", text: "He never explicitly approved it." },
      { type: "paragraph", text: "He also never told me to remove it." },
      { type: "pullquote", accent: true, text: "I recorded the outcome as compliant." },
      { type: "doodle", art: "tripod" },
      { type: "section-heading", text: "Final disposition" },
      { type: "paragraph", text: "When I moved to a room with usable Wi-Fi, I donated the assembly to a friend down the hall. I handed over the can, tripod, adapter, cable, and aiming marks." },
      { type: "dialogue", lines: ["He asked whether campus housing knew about it.", "I said they had seen it."] },
      { type: "paragraph", text: "The access point was never moved. The IT ticket achieved nothing. The Pringles can worked for the whole semester and then began a second deployment." },
      { type: "status", lines: ["Status: Device transferred.", "Status of university infrastructure: Spiritually unchanged."] },
    ],
  },
  {
    id: "elevator-debug",
    title: "The Elevator at 3 AM",
    meta: "packet captures / a phantom floor request / one quiet report",
    teaser: "A badge reader and an elevator were arguing over a subnet during a 36-hour hackathon.",
    readingTime: "Estimated reading time: 3 minutes",
    blocks: [
      { type: "section-heading", text: "2:47 AM" },
      { type: "paragraph", text: "Thirty hours into a 36 hour hackathon, everyone in the building had split into three categories." },
      { type: "beats", lines: ["People still coding.", "People asleep under tables.", "People saying \"we should pivot\" because their original idea had died six hours ago and nobody wanted to admit it."] },
      { type: "paragraph", text: "I was in the first category, mostly because the elevator would not let me leave." },
      { type: "paragraph", text: "It had been acting possessed all night. It would stop at floor two with nobody there, open its doors, wait, close them, then immediately go to floor three. Sometimes it skipped the floor you selected. Sometimes it arrived, opened, and changed its mind halfway through." },
      { type: "pullquote", text: "It was less vertical transportation and more a metal box exploring free will." },
      { type: "paragraph", text: "Facilities had already been called. They said a technician could come Monday." },
      { type: "beats", lines: ["It was Saturday morning.", "Excellent."] },
      { type: "doodle", art: "elevator" },
      { type: "section-heading", text: "3:06 AM" },
      { type: "paragraph", text: "I was walking back from refilling my water bottle when the elevator opened on floor three by itself." },
      { type: "beats", lines: ["Nobody got out.", "Nobody got in."] },
      { type: "paragraph", text: "Across the hallway, the new badge reader flashed." },
      { type: "paragraph", text: "The elevator doors closed." },
      { type: "paragraph", text: "That was suspicious enough to temporarily overpower my need for sleep." },
      { type: "paragraph", text: "I stood there and waited." },
      { type: "paragraph", text: "Someone tapped their badge." },
      { type: "paragraph", text: "The reader beeped." },
      { type: "paragraph", text: "A few seconds later, the elevator moved." },
      { type: "paragraph", text: "I watched it happen again." },
      { type: "paragraph", text: "This was not proof. At 3 AM, a correlation can be either a discovery or your brain beginning to liquefy. So I went back upstairs, opened my laptop, and started checking what was visible from the building network." },
      { type: "paragraph", text: "The elevator controller was broadcasting status traffic. Nothing secret or magical. Just routine state messages announcing things like current floor, direction, door state, and pending requests." },
      { type: "paragraph", text: "I connected through the normal building Ethernet port and opened Wireshark." },
      { type: "beats", lines: ["I did not send commands.", "I did not touch the control cabinet.", "I did not attempt to operate the elevator from my laptop, because I enjoy debugging things but not appearing in a facilities incident report under the heading \"student created new problem.\""] },
      { type: "pullquote", text: "I only listened." },
      { type: "doodle", art: "badge" },
      { type: "section-heading", text: "3:31 AM" },
      { type: "paragraph", text: "At first, the packet capture looked like what all packet captures look like when you are exhausted." },
      { type: "beats", lines: ["Numbers.", "Addresses.", "Repeated messages.", "A digital landfill with timestamps."] },
      { type: "paragraph", text: "I filtered for broadcast and multicast traffic, then separated packets by source address. The elevator controller had a predictable rhythm. It reported its state, received a request, updated the queue, moved, and reported the new state." },
      { type: "paragraph", text: "Then another device appeared." },
      { type: "paragraph", text: "It had been added recently. Its traffic spiked every time someone used the badge reader on floor three." },
      { type: "paragraph", text: "That alone was normal. Badge readers generate events. Buildings like knowing who is entering which doors, partly for security and partly because apparently every hallway now needs analytics." },
      { type: "paragraph", text: "The problem was what happened next." },
      { type: "paragraph", text: "Each badge event was followed by a message that matched the structure of an elevator floor request closely enough that the controller appeared to accept it." },
      { type: "sequence", lines: ["Badge tapped.", "Packet emitted.", "Floor three entered the queue."] },
      { type: "pullquote", text: "The elevator was not haunted. It was being summoned by access control." },
      { type: "doodle", art: "packet" },
      { type: "section-heading", text: "4:18 AM" },
      { type: "paragraph", text: "I needed to make sure I was not inventing a pattern because I had consumed enough caffeine to hear Ethernet frames emotionally." },
      { type: "paragraph", text: "So I started logging events." },
      { type: "beats", lines: ["Badge reader flash.", "Packet timestamp.", "Elevator request update.", "Elevator movement.", "Again.", "Again.", "Again."] },
      { type: "paragraph", text: "The sequence was consistent." },
      { type: "paragraph", text: "The new reader and the elevator system were on the same building automation subnet. Somewhere in the integration, the reader gateway was broadcasting an event with an identifier or message mapping that overlapped with the elevator controller's request format." },
      { type: "pullquote", text: "The elevator was doing exactly what it had been told to do." },
      { type: "paragraph", text: "The instructions were just coming from the wrong rectangle on the wall." },
      { type: "section-heading", text: "5:02 AM" },
      { type: "paragraph", text: "I could not safely fix it myself, and I had no authorization to reconfigure either system." },
      { type: "paragraph", text: "So I did the least dramatic and most useful thing possible." },
      { type: "pullquote", text: "I wrote documentation." },
      { type: "paragraph", text: "I included a subnet diagram, the source addresses, timestamps, packet captures, the repeated sequence, and the device I believed was causing the conflict. I marked clearly that I had performed passive observation only." },
      { type: "paragraph", text: "I also suggested what facilities should check." },
      { type: "list", items: ["Separate the access control device from the elevator traffic.", "Verify the gateway mapping.", "Check for a duplicated device identifier.", "Confirm whether badge events were being translated into destination calls."] },
      { type: "paragraph", text: "Then I printed the report and left it at the facilities desk, because emailing someone at 5 AM during a hackathon would have made the whole thing look significantly more unhinged." },
      { type: "doodle", art: "report" },
      { type: "section-heading", text: "Tuesday" },
      { type: "paragraph", text: "The elevator was working normally." },
      { type: "beats", lines: ["No random floors.", "No doors opening for ghosts.", "No spontaneous pilgrimage to floor three every time somebody entered the hallway."] },
      { type: "paragraph", text: "Nobody asked me about the report." },
      { type: "paragraph", text: "Nobody asked why a student had packet captures of an elevator at 4 AM." },
      { type: "paragraph", text: "I decided this was probably the best possible outcome." },
      { type: "paragraph", text: "The hackathon project itself did not win." },
      { type: "closing", lines: ["The building, however, regained reliable vertical transportation.", "There was no prize category for that."] },
    ],
  },
];

export const contactLinks = {
  github: "https://github.com/tejasnaladala",
  linkedin: "https://www.linkedin.com/in/tejasnaladala",
  instagram: "https://www.instagram.com/tejasnaladala/",
  scholar: "https://scholar.google.com/citations?user=7901XFQAAAAJ",
  email: "mailto:naladala@uw.edu?subject=Hello%20Tejas",
  pitch: "mailto:naladala@uw.edu?subject=Angel%20pitch%20-%20%5BCompany%5D",
  foundersInc: "https://f.inc/",
  speedrun: "https://speedrun.a16z.com/",
  resume: "./assets/resume.pdf?v=20260901.13",
};
