export const aboutNarrative = {
  roots: [
    [
      "My roots lie in a ",
      { text: "small coastal village in South India", mark: true, tone: "green", color: true },
      ".",
    ],
    [
      "My family farmed for generations. We grew chilli, tobacco, and other food crops. I grew up with all of it. The land, the crops, the people, the chemicals, the machines, and even the money problems in a traditional Indian family dynamic.",
    ],
  ],
  education: [
    [
      "I now study engineering at the ",
      { text: "University of Washington", mark: true, tone: "blue" },
      ", though I don't really believe in formal education.",
    ],
    [
      "Academically, I was far from exceptional. I never cared enough to study for grades. My dad once dropped a course and retook it the next semester because he got a ",
      "97 instead of a 100",
      ". That was why we couldn't ever have a peaceful relationship while I was growing up. He was a perfectionist. I believed ",
      { text: "imperfections were sometimes what made things perfect", mark: true, tone: "pink" },
      ".",
    ],
  ],
  stage: [
    [
      "I fell in love with the art of ",
      { text: "\"fuck around and find out\"", mark: true, tone: "coral", color: true },
      ".",
    ],
    [
      "I cared about completely different things. I would break open my ceiling fan to see if I could make it spin in reverse. I would try building my own hydroponic irrigation system. I would change how my coffee machine brewed coffee. I would try Pavloving different animals into doing chores for me. Yes, my dog is more capable than a $20,000 ",
      { text: "Unitree G1", href: "https://robostore.com/products/unitree-g1-robotic-humanoid", tone: "coral" },
      " at doing laundry.",
    ],
    [
      "I picked up ",
      { text: "beatboxing", href: "https://en.wikipedia.org/wiki/Beatboxing", tone: "gold" },
      ", then dance, street plays, drama, debate, and pageants. I performed in front of ",
      { text: "tens of thousands of people", mark: true, tone: "pink" },
      ". I led blood, book, and clothing donation drives. I led a thousand students as school captain.",
    ],
    "I loved it. I loved being on stage. I loved people. I loved making people laugh. I loved being the chaos and also being the person who could hold it together.",
    "I started doing things that made me happy.",
    [
      "and somewhere along the way, I ",
      { text: "fell in love with problems", mark: true, tone: "rose" },
      ".",
    ],
  ],
  freedomIntro: [
    { text: "entrepreneurship", mark: true, tone: "coral" },
    " speaks to me",
  ],
  freedom: [
    "Freedom to not have my entire life decided for me or imposed upon me because of societal norms.",
    "Freedom to become obsessed with something nobody around me understands yet.",
    "Freedom to build something because I think it should exist.",
    "Freedom to change direction when I realise I was wrong.",
    "Freedom to work with people I actually respect.",
    "Freedom to fail on my own terms.",
    "Freedom to change lives.",
    "Freedom to be me.",
  ],
  freedomClose: "So I started building.",
  builds: [
    {
      label: "power",
      content: [
        "I have built ",
        { text: "high-voltage power electronics", mark: true, tone: "gold" },
        " and sold plasma reactors.",
      ],
    },
    {
      label: "sensing",
      content: [
        "I built hull-integrity sensing hardware for a ",
        { text: "U.S. Navy", mark: true, tone: "blue" },
        " project and deployed subsea instrumentation in the Pacific.",
      ],
    },
    {
      label: "ocean",
      content: [
        "I built computer-vision and event-logging pipelines during work with ",
        { text: "WHOI", href: "https://www.whoi.edu/", tone: "blue" },
        ", ",
        { text: "NSF's OOI", href: "https://oceanobservatories.org/", tone: "sky" },
        ", and UW ",
        { text: "APL", href: "https://www.apl.washington.edu/", tone: "green" },
        ".",
      ],
    },
    {
      label: "fieldwork",
      content: [
        "I surveyed the Axial Seamount, the most active underwater volcano in the Pacific Northwest, 300 miles off the coast of Oregon, using an ",
        { text: "11,000-pound robot", href: "https://www.whoi.edu/what-we-do/explore/underwater-vehicles/ndsf-jason/", tone: "blue" },
        ".",
      ],
    },
    {
      label: "scale",
      content: [
        "At ",
        { text: "OpenTrade", href: "https://opentrade.live/", tone: "green" },
        ", I built the model-evaluation and ranking stack for a product that reached ",
        { text: "0 to 150,000 users in two months", mark: true, tone: "coral" },
        ".",
      ],
    },
    {
      label: "benchmarks",
      content: [
        "I collaborated on ",
        { text: "MTEB", href: "https://pypi.org/project/mteb/", tone: "pink" },
        ". The package reached roughly ",
        { text: "17 million PyPI downloads by August 2026", mark: true, tone: "pink" },
        ".",
      ],
    },
    {
      label: "empiricism",
      content: [
        "I built a knee-MRI research pipeline around a ",
        { text: "Radiological Society of North America", href: "https://www.rsna.org/", tone: "sky" },
        " challenge dataset.",
      ],
    },
    {
      label: "materials",
      content: [
        "I fabricated and characterised ",
        { text: "dye-sensitised solar-cell architectures", mark: true, tone: "green" },
        " with ",
        { text: "the group behind the world-record efficiency", href: "https://www.niist.res.in/", tone: "gold" },
        ".",
      ],
    },
    {
      label: "publications",
      content: [
        "I published ",
        { text: "3 peer-reviewed papers", mark: true, tone: "coral" },
        ", 2 technical reports, and presented at an international conference.",
      ],
    },
  ],
  questions: [
    [
      "I'm also intrigued by psychedelics, ego death, consciousness, religion, God, ambition, love, and ",
      { text: "what it means to be human", mark: true, tone: "green" },
      ".",
    ],
    "Spirituality often confuses me.",
    [
      { text: "Curiosity", mark: true, tone: "green", color: true },
      " is the only thing tying this page together.",
    ],
  ],
  ending: [
    "I'm getting at something here. I promise.",
  ],
};

export const angelProfile = {
  title: "Angel Desk",
  eyebrow: "PERSONAL CHECKS / VERY EARLY",
  thesis: [
    {
      id: "agentic-commonwealth",
      label: "Agentic Commonwealth",
      definition: "Core infrastructure for intelligent systems: agent platforms, data systems, developer tooling, future-of-work software, and agent optimization through reinforcement learning.",
    },
    {
      id: "american-dynamism",
      label: "American Dynamism",
      definition: "Technologies that expand industrial capacity and strategic resilience across advanced manufacturing, energy, aerospace, and uncrewed systems.",
    },
    {
      id: "kinetic-sovereignty",
      label: "Kinetic Sovereignty",
      definition: "Deeptech and hardtech that translate intelligence into physical capability across climate, agriculture, robotics, and physical AI.",
    },
  ],
  lead: "I write personal $5K-$30K checks into very early technical teams.",
  paragraphs: [
    "I am most useful before the story gets polished. I love it when technical insight does most of the talking.",
    "No warm introductions are required, but managing to find one gets you brownie points.",
    "I don't care for decks. A Google Doc is more than enough. Clarity of thought is what I look for.",
  ],
  referral: "If I like you but I'm not in a position to fund you, I will personally refer you to investment partners at Founders, Inc. and a16z Speedrun.",
  scorecardIntro: "There is no formula for predicting which startups become unicorns, but these signals make me want to hop on a Google Meet with you. I call it the 20-point rule.",
  signals: [
    { label: "Team synergy & story", score: "+5" },
    { label: "High agency and proof of building, failing, and learning", score: "+4" },
    { label: "Honesty & asking for help", score: "+4" },
    { label: "A technical edge", score: "+2" },
    { label: "A non-cliched contrarian take on the world", score: "+1" },
    { label: "A working artifact, however ugly", score: "+1" },
    { label: "Evidence-backed pivots", score: "+1 each, max +3" },
  ],
};

export const archiveEntries = [
  {
    id: "nespresso-jailbreak",
    title: "the nespresso jailbreak",
    meta: "coffee / optical codes / unreasonable persistence",
    teaser: "I reverse-engineered the five-parameter barcode around a Vertuo pod, then generated my own recipes.",
    readingTime: "Estimated reading time: 4 minutes 34 seconds",
    blocks: [
      { type: "paragraph", text: "My dad owns a Nespresso Vertuo, and I am the kind of person who loves coffee more than I loved my ex. Not in the normal \"I am addicted to caffeine or I can't take a shit in the morning\" way. I mean Nikki-level obsession, from the movie Obsession." },
      { type: "paragraph", text: "The Vertuo should have been perfect for me: insert a capsule, press a button, get coffee, drink. Instead, the simplicity annoyed the \"shit\" out of me, pun intended." },
      { type: "paragraph", text: "Around the underside of every capsule's rim is a ring of black and reflective marks. An optical reader scans that ring, and the machine uses it to choose the brew program, which, as I figured, included water volume, temperature, flow, pre-infusion time, and capsule rotation. Nespresso describes those same controls as \"capsule-specific extraction parameters.\"" },
      { type: "pullquote", text: "Most people see convenience." },
      { type: "pullquote", text: "I saw a machine being forced to obey instructions from a sticker. And me being forced to the same five coffee flavours." },
      { type: "doodle", art: "capsule-code" },
      { type: "paragraph", text: "I started collecting used capsules. My mom said she'd lend me an extra $50 if I was in need. I washed them, dried them, labelled them, and photographed the code rings. The first images were useless, with curved bars, glare from the foil, dents in the rim, and tiny camera-angle changes that distorted the widths." },
      { type: "paragraph", text: "I wrote a small image-processing script that found the circular rim, sampled a narrow annulus around it, and \"unwrapped\" the circle into a straight strip. I thresholded it, measured run lengths, and compared the repeating sections." },
      { type: "doodle", art: "unwrap" },
      { type: "paragraph", text: "Then came the slower part. A code can be decoded only if you know what its symbols correspond to, and the coffee itself was a confounding variable. Official capsules differ in grind, dose, roast, and coffee-bed resistance. If one brewed more slowly than another, I couldn't blame the barcode." },
      { type: "paragraph", text: "So I built controls." },
      { type: "paragraph", text: "I cleaned several capsule shells, filled them with the same coffee at the same grind and dose, sealed them as consistently as I could, and changed the code ring while keeping the coffee bed fixed." },
      { type: "question", text: "The research question: when the physical contents stay approximately constant, what does changing only the code make the machine do?" },
      { type: "paragraph", text: "My kitchen became a very small, very caffeinated test bench." },
      { type: "doodle", art: "test-bench" },
      { type: "paragraph", text: "A scale under the cup gave me beverage mass instead of an eyeballed mug measurement. A temperature probe near the outlet recorded the liquid's temperature profile; mass over time gave me the flow curve. The delay between the cycle's beginning and the first sustained liquid reaching the cup gave me an approximate measure of pre-infusion and startup timing." },
      { type: "paragraph", text: "Spin speed was the least cooperative parameter." },
      { type: "paragraph", text: "I could hear that different capsules produced different motor profiles. I recorded the machine and examined the frequency spectrum of the motor whine. Its dominant frequency gave me a consistent proxy for relative rotational speed." },
      { type: "paragraph", text: "It was not a factory-calibrated tachometer, but it was enough to distinguish different spin stages." },
      { type: "doodle", art: "spectrum" },
      { type: "paragraph", text: "At this point I was proud enough of myself, and wanted to see if anyone was hiring a reverse-engineering intern." },
      { type: "pullquote", text: "This optical pattern produces this volume class. This one produces this timing profile. This section appears to affect temperature. This combination changes the machine's relative rotation behaviour." },
      { type: "paragraph", text: "Enough pods began to form clusters. I compared pairs, looked for segments that stayed fixed when an output stayed fixed, and tracked which segments changed when one observable shifted." },
      { type: "paragraph", text: "Once I could move from barcode to behaviour, I tried to move backward, from desired behaviour to barcode." },
      { type: "paragraph", text: "Eventually, I pressed the button and the machine accepted one." },
      { type: "sequence", lines: ["It spun.", "Paused.", "Infused.", "Accelerated.", "And poured."] },
      { type: "paragraph", text: "It saw a sufficiently valid optical instruction and executed it." },
      { type: "doodle", art: "brew" },
      { type: "paragraph", text: "From there, I generated a small library of custom profiles within the machine's existing operating envelope: a shorter, more concentrated brew; a gentler profile for a lighter roast; and a longer cup that did not simply drown the grounds in water." },
      { type: "paragraph", text: "I applied the rings to third-party shells and changed one variable at a time. Some recipes were terrible." },
      { type: "paragraph", text: "All of them taught me something." },
      { type: "paragraph", text: "This was about refusing to accept that the button was the end-all, be-all of the system." },
      { type: "stack", lines: ["Behind the button was an optical sensor.", "Behind the sensor was a code.", "Behind the code was a control policy.", "Behind the control policy were assumptions about what kinds of coffee I was allowed to make.", "And assumptions are always invitations."] },
      { type: "doodle", art: "policy" },
      { type: "paragraph", text: "This is an unreasonable amount of effort to spend on a cup of coffee. That is exactly why I love the story." },
      { type: "closing", lines: ["It was just coffee.", "It is never just coffee."] },
    ],
  },
  {
    id: "wifi-cantenna",
    title: "the cantenna incident",
    meta: "2.4 GHz / a Pringles can / dorm engineering",
    teaser: "The dorm Wi-Fi was unusable, so I built a directional antenna and pointed it through two concrete walls.",
    readingTime: "Estimated reading time: 4 minutes 52 seconds",
    blocks: [
      { type: "pullquote", text: "\"Unauthorized Use of Snack Packaging as Network Infrastructure\" was my first dorm violation as a freshman." },
      { type: "paragraph", text: "Freshman year, I was assigned a dorm room on the far side of the building, which apparently meant the far side of modern civilization." },
      { type: "paragraph", text: "The Wi-Fi signal at my desk averaged around -85 dBm. On a good day." },
      { type: "paragraph", text: "-85 dBm means your laptop is technically connected, but only because neither party has had the courage to end the relationship. Canvas loaded one rectangle at a time. Video calls made me look like a police sketch. Submitting an assignment at 11:58 became a live demonstration of probability theory." },
      { type: "paragraph", text: "I sent campus IT screenshots, signal readings, and the room location." },
      { type: "paragraph", text: "Their answer was that the access point could not be moved. Their proposed fix was that I could work in the common area." },
      { type: "pullquote", text: "Incredible. Years of networking research, billions of wireless devices, and the solution was still \"go sit somewhere else.\"" },
      { type: "paragraph", text: "I tried everything normal first. I moved the desk, changed adapter settings, and tested the signal by the door, window, and ceiling. At one point I was standing on a chair holding my laptop above my head, which is usually when an engineering solution stops looking intelligent." },
      { type: "paragraph", text: "The signal improved slightly in one upper corner. That was enough. There was a path into the room. It was just weak, ugly, and probably bouncing through the hallway before arriving." },
      { type: "doodle", art: "wifi" },
      { type: "section-heading", text: "Proposed corrective action" },
      { type: "pullquote", accent: true, text: "Build a directional antenna." },
      { type: "paragraph", text: "Not hack the network. Not steal a password. Not build a jammer. Nothing sexy enough for a disciplinary hearing." },
      { type: "paragraph", text: "A normal laptop antenna listens in several directions. I knew roughly where the access point was. A directional antenna could trade broad coverage for gain in the one direction I cared about." },
      { type: "paragraph", text: "I started reading about cantennas, which are exactly what the name suggests: antennas made from cans." },
      { type: "paragraph", text: "The classic design uses a conductive cylinder as a circular waveguide. A probe inside excites the field, the sealed end acts as a reflector, and the open end gives the antenna directionality." },
      { type: "paragraph", text: "At 2.4 GHz, the free-space wavelength is about 125 millimetres. A quarter wavelength is a little over 30 millimetres, which gave me the initial probe length. The feed position depends on the guide wavelength inside the cylinder, which depends on its diameter and cutoff frequency." },
      { type: "pullquote", text: "This is where I discovered that most tutorials treat \"can\" as a legally sufficient unit of measurement. It is not." },
      { type: "paragraph", text: "A Pringles tube is not an ideal waveguide either. Its diameter sits close to the lower practical limit for 2.4 GHz, and its conductive lining is considerably less impressive once you attack it with a multimeter." },
      { type: "paragraph", text: "I considered buying a proper metal can." },
      { type: "paragraph", text: "Then I remembered the project was already funny." },
      { type: "doodle", art: "cantenna" },
      { type: "section-heading", text: "Bill of materials" },
      { type: "list", items: ["One Pringles can.", "One N-type bulkhead connector.", "One SMA pigtail.", "One USB Wi-Fi adapter with an external antenna port.", "Copper wire and copper tape.", "A camera tripod.", "One multimeter.", "A completely unjustified level of confidence."] },
      { type: "paragraph", text: "The chips did not contribute electrically, but I ate them during design review." },
      { type: "doodle", art: "chips" },
      { type: "section-heading", text: "Construction notes" },
      { type: "paragraph", text: "I checked continuity across the inner lining and reinforced weak sections with copper tape. I wanted the cylinder, base, and connector body to behave as one conductive structure rather than three objects loosely sharing a snack logo." },
      { type: "paragraph", text: "I soldered copper wire to the centre pin of the N-type connector and trimmed it toward a quarter wavelength. I left it slightly long because wire can always be shortened. It cannot be emotionally encouraged to grow back." },
      { type: "paragraph", text: "I marked the feed hole about 45 millimetres from the sealed end, based on the dimensions and design I was adapting. I measured it three times, then another four because drilling into cardboard should not have felt this permanent." },
      { type: "paragraph", text: "The connector went through the tube. The SMA pigtail ran to the USB adapter. The adapter plugged into my laptop." },
      { type: "paragraph", text: "I was not going to claim the finished antenna had exactly 12 dBi of gain. I did not own a calibrated reference antenna, a network analyser, or an anechoic chamber. People throw precise gain numbers around online because confidence is free." },
      { type: "paragraph", text: "What I could measure was whether the link got better." },
      { type: "doodle", art: "connector" },
      { type: "section-heading", text: "Test procedure" },
      { type: "paragraph", text: "I mounted the antenna on a camera tripod and opened a signal monitor. The tripod let me adjust direction, elevation, and polarization without holding a Pringles can perfectly still for twenty minutes. It also made the device look official, which is an underappreciated part of engineering." },
      { type: "beats", lines: ["I swept it slowly across the wall.", "Nothing.", "I changed the elevation.", "Still nothing.", "I rotated it slightly past where I thought the access point should be.", "The signal jumped.", "I turned away. It dropped.", "I turned back. It rose again."] },
      { type: "pullquote", accent: true, text: "This was the first time a Pringles can had given me positive experimental results instead of salt." },
      { type: "paragraph", text: "The best direction was slightly off to one side, probably because the useful signal was reflecting through a doorway or corridor rather than travelling directly through two concrete walls like the Kool-Aid Man." },
      { type: "paragraph", text: "I adjusted the angle in small increments, rotated the polarization, shortened the cable to reduce loss, and raised the tripod. Every time the signal improved, I marked the position with tape." },
      { type: "paragraph", text: "My roommate asked why." },
      { type: "pullquote", text: "Because optimization is useless if some idiot bumps the tripod while looking for socks." },
      { type: "doodle", art: "spectrum" },
      { type: "section-heading", text: "Results" },
      { type: "paragraph", text: "The connection went from barely alive to stable enough for actual work." },
      { type: "paragraph", text: "The signal climbed out of the -80s. Packet loss fell. Latency stopped spiking whenever I attempted something more demanding than opening a text file. The best speed tests reached about 150 Mbps, although dorm traffic still moved the number around." },
      { type: "paragraph", text: "That was fine. I was not providing internet to the International Space Station. I wanted Canvas to open before I graduated." },
      { type: "paragraph", text: "The cantenna stayed mounted for the entire semester." },
      { type: "section-heading", text: "Housing review" },
      { type: "paragraph", text: "One afternoon, the RA walked in and stared at the tripod." },
      { type: "dialogue", lines: ["\"What is that?\"", "\"An art project.\"", "He looked at the cable.", "\"What kind of art?\"", "\"Site specific.\"", "He kept staring."] },
      { type: "paragraph", text: "I explained that it was a passive directional antenna connected to my own Wi-Fi adapter. I was not modifying the adapter's transmit power, attacking the network, or touching anyone else's connection. I had simply built a better radio link for the signal already reaching my room." },
      { type: "paragraph", text: "He never explicitly approved it." },
      { type: "paragraph", text: "He also never told me to remove it." },
      { type: "pullquote", accent: true, text: "I recorded the outcome as compliant." },
      { type: "doodle", art: "tripod" },
      { type: "section-heading", text: "Final disposition" },
      { type: "paragraph", text: "When I moved to a room with usable Wi-Fi, I donated the assembly to a friend down the hall. I handed over the can, tripod, adapter, cable, and aiming marks." },
      { type: "dialogue", lines: ["He asked whether campus housing knew about it.", "I said they had seen it."] },
      { type: "paragraph", text: "The access point was never moved. The IT ticket achieved nothing. The Pringles can worked for the whole semester and then began a second deployment." },
      { type: "status", lines: ["Status: Device transferred.", "Status of university infrastructure: Spiritually unchanged."] },
    ],
  },
];
